repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
        - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace # remove trailing whitespace
    -   id: end-of-file-fixer # ensure newline at end of file
    -   id: check-yaml # verify yaml files
    -   id: check-toml # verify toml files
    -   id: check-added-large-files # prevent large files from being committed
    -   id: check-merge-conflict # check for files that contain merge conflict strings
    -   id: detect-private-key # check for private keys
    -   id: debug-statements # check for debugger statements
        language_version: python3

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
        - id: codespell
          args:
              - --skip=*.css,*.js,*.map,*.scss,*.svg
              - --ignore-words-list=magent,pres,roate

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
        - id: isort
          args: [--profile, black]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

  - repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest
        args: ['-s', '-x', 'tests']
        language: system
        pass_filenames: false
        always_run: true
