[project]
name = "microvault"
dynamic = ["version"]
description = "A simple navigation with reinforcement learning"
keywords = ["RL", "navigation", "deep learning"]


authors = [{name = "Nicolas Alan", email = "grottimeireles@gmail.com"}]
readme = "README.md"
license = {file = "LICENSE"}
maintainers = [
  {name = "Nicolas Alan", email = "grottimeireles@gmail.com"}
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: File Transfer Protocol (FTP)",
    "Topic :: System :: Networking"
]
requires-python = ">= 3.10"

dependencies = [
  "tdqm",
]
