[tool.poetry]
name = "microvault"
version = "0.2.33"
description = "Microvault - RL for Navigation"
authors = ["Nicolasalan <grottimeireles@gmail.com>"]
license = "LICENSE"
readme = "README.md"
packages = [{ include = "microvault" }]

[tool.poetry.urls]
documentation = "https://microvault.readthedocs.io"
bugs = "https://github.com/microvault/microvault/issues"

[tool.poetry.dependencies]
python = "^3.10"
accelerate = "^0.18.0"
fastrand = ">=1.3,<3.0"
hydra-core = "^1.3.2"
matplotlib = "^3.4.3"
numpy = "^1.24.2"
omegaconf = "^2.3.0"
torch = "^2.0.1"
pymunk = "^6.6.0"
psutil = "^5.9.8"
wget = "^3.2"
scikit-image = "*"
numba = ">=0.59.1,<0.61.0"
gym = "^0.26.2"
shapely = ">=1.8,<3.0"
wandb = "^0.17.5"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"
black = "^24.1.1"
isort = "^5.13.2"
ruff = "^0.2.1"
codespell = "^2.2.6"
commitizen = "^3.14.1"
pre-commit = "^3.7.0"

# [tool.poetry.group.doc.dependencies]
# furo = "2024.4.27"
# sphinx = "7.3.7"
# sphinx-toolbox = "3.5.0"
# sphinx-notfound-page = "1.0.0"

[tool.pytest.ini_options]
pythonpath = "."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
