sensor:
  min_fov: 10
  max_fov: 180
  min_num_rays: 10
  max_num_rays: 60
  min_min_range: 0.5
  max_min_range: 3.0
  min_max_range: 3.0
  max_max_range: 10.0

robot:
  min_base_radius: 0.01
  max_base_radius: 0.1
  min_vel_linear: [0.0, 0.5]
  max_vel_linear: [0.5, 2.0]
  min_vel_angular: [-1.0, -0.5]
  max_vel_angular: [0.5, 1.0]
  min_wheel_distance: 0.1
  max_wheel_distance: 0.3
  min_weight: 0.5
  max_weight: 2.0
  min_threshold: 0.1
  max_threshold: 0.5

environment:
  min_timestep: 500
  max_timestep: 3000
  min_step: 500
  max_step: 3000
  min_grid_dimension: 3
  max_grid_dimension: 10
  min_friction: 0.1
  max_friction: 0.9
  min_porcentage_obstacles: 0.1
  max_porcentage_obstacles: 0.9
  min_randomization_interval: 10
  max_randomization_interval: 100
