env:
  scalar: 20
  folder_map:
  name_map:
  timestep: 50
  obstacle_percentage: 50
  map_size: 3
  type: turn
  grid_size: [1.5, 1.5]

render:
  controller: false
  debug: true
  plot: false

sensor:
  fov: 90.0
  num_rays: 3
  min_range: 0.0
  max_range: 5.0

robot:
  base_radius: 0.105
  vel_linear: [0.0, 0.22]
  vel_angular: [1.0, 2.84]
  wheel_distance: 0.16
  weight: 1.0
  threshold: 0.10
  collision: 0.05
  path_model:

network:
  hidden_size: [32, 32]
  mlp_activation: ReLU
  type_model: MlpPolicy

trainer:
  pretrained: None
  use_agents: false
  # max_timestep_global: 1000
  max_timestep_global: 200000
  seed: 1
  batch_size: 64
  lr: 1e-4
  num_envs: 12
  device: mps
  learn_step: 256
  checkpoint: 10000
  checkpoint_path: ./checkpoint_models
  use_wandb: false
  wandb_api_key: YOUR_WANDB_KEY
  llm_api_key: YOUR_OPENAI_KEY
  gae_lambda: 0.90
  ent_coef: 0.02
  vf_coef: 0.4
  max_grad_norm: 0.5
  update_epochs: 3
  clip_range_vf: 0.2
  target_kl: 0.025
  name: robot_nav_skills
  verbose: true
  policy_type: PPO
