env:
  scalar: 7
  folder_map:
  name_map:
  timestep: 1000
  obstacle_percentage: 50
  map_size: 3
  type: train-mode
  grid_size: [1.5, 1.5]

render:
  controller: false
  debug: true
  plot: false

sensor:
  fov: 270.0
  num_rays: 5
  min_range: 0.001
  max_range: 3.5

robot:
  base_radius: 0.105
  vel_linear: [0.0, 0.22]
  vel_angular: [1.0, 2.84]
  wheel_distance: 0.16
  weight: 1.0
  threshold: 0.10
  collision: 0.010
  path_model:

network:
  hidden_size: [64, 64]
  mlp_activation: ReLU
  type_model: MlpPolicy

trainer:
  pretrained: None
  use_agents: false
  max_timestep_global: 1_000_000
  seed: 1
  batch_size: 128
  lr: 0.0003
  num_envs: 8
  device: mps
  learn_step: 512
  checkpoint: 10000
  checkpoint_path: ./checkpoint_models
  use_wandb: false
  wandb_api_key: YOUR_WANDB_KEY
  llm_api_key: YOUR_OPENAI_KEY
  gae_lambda: 0.95
  ent_coef: 0.02
  vf_coef: 0.5
  max_grad_norm: 0.5
  update_epochs: 6
  name: robot_nav_skills
  verbose: true
  policy_type: PPO
