wandb:
  project: rl-navigation
  entity:
  mode: online

agent:
  desc: "TD3"
  gamma: 0.99
  tau: 1e-3
  update_every_step: 2
  lr_actor: 1e-3
  lr_critic: 1e-3
  noise: 0.2
  noise_clip: 0.5
  nstep: 10
  weight_decay: 0.0

noise_layer:
  desired_distance: 0.7
  scalar: 0.05
  scalar_decay: 0.99

replay_buffer:
  buffer_size: 1048576

environment:
  timestep: 100
  size: 2.0
  fps: 50
  random: 100000000000
  threshold: 0.005
  grid_lenght: 10 # TODO: error < 5 -> [5 - 15]
  state_size: 13
  action_size: 2

robot:
  min_radius: 1.0
  max_radius: 3.0
  wheel_radius: 0.3
  wheel_base: 0.3
  fov: 6.28
  num_rays: 10
  max_range: 6.0
  max_action: 1.0
  min_action: -1.0
  max_linear: 1.0 # 0.2 m/s
  min_linear: 0.0 # 0.1 m/s
  max_angular: 1.0 # 0.2 rad/s
  min_angular: -1.0 # 0.1 rad/s

engine:
  seed: 42
  device: cpu
  batch_size: 128
  num_episodes: 2000
  pretrained: False
  checkpoint: 200
  path: "./"
  wandb: True
  save_checkpoint: 200
  epochs: 1000
  visualize: False

network:
  layers_actor_l1: 400
  layers_actor_l2: 300
  layers_critic_l1: 400
  layers_critic_l2: 300
