method: bayes
metric:
  goal: maximize
  name: mean_reward
parameters:
  learning_rate_actor:
    min: 0.0001
    max: 0.1
  learning_rate_critic:
    min: 0.0001
    max: 0.1
  batch_size:
    values: [32, 128, 256]
  epochs:
    values: [500, 1000, 1500]
  noise:
    min: 0.1
    max: 0.5
  nstep:
    values: [1, 5, 10]
  weight_decay:
    min: 0.0
    max: 0.1
  noise_std:
    min: 0.01
    max: 0.5
  seed:
    values: [42, 43, 44, 45, 46, 47, 48, 49, 50]
  layers_actor_l1:
    values: [200, 300, 400]
  layers_actor_l2:
    values: [100, 200, 300]
  layers_critic_l1:
    values: [200, 300, 400]
  layers_critic_l2:
    values: [100, 200, 300]

early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27
