name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'
  Build:
    needs: [Checkout]
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Update pip and install poetry
        run: python -m pip install --upgrade pip && pip install poetry
      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory: $(ls)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
      - name: Install dependencies
        run: poetry install
  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          poetry run task test --cov-report=xml
