name: Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update pip and install poetry
        run: python -m pip install --upgrade pip && pip install poetry

      - name: Update poetry.lock
        run: poetry lock --no-update

      - name: Install dependencies
        run: make install

      # - name: Run tests
      #   run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Build-MacOS:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update pip and install poetry
        run: python -m pip install --upgrade pip && pip install poetry

      - name: Update poetry.lock
        run: poetry lock --no-update

      - name: Install dependencies
        run: make install

      # - name: Run tests
      #   run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Update pip and install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Update poetry.lock
        run: poetry lock --no-update

      - name: Install dependencies
        run: poetry install

      # - name: Run tests
      #   run: poetry run pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  # Push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: login to ghcr.io
  #       run: echo "${{ secrets.GHCR }}" | docker login ghcr.io -u rnl --password-stdin

  #     - name: Build image
  #       run: docker build -t ghcr.io/microvault/rnl:latest .

  #     - name: Push image
  #       run: docker push ghcr.io/microvault/rnl:latest
